
import React, { useState, useEffect, useCallback } from 'react';
import type { GeneratedAssets, ScriptBlock, Scene, Character, VisualStyle, RewriteTomorrowTheme, EmotionalArcIntensity, NarrativeTone } from '../../types';
import { LogoIcon } from '../icons/LogoIcon';
import { CharactersSection } from './CharactersSection';
import { ScriptSection } from './ScriptSection';
import { VisualOutlineSection } from './VisualOutlineSection';
import { MoodboardSection } from './MoodboardSection';
import { BtsSection } from './BtsSection';
import { OutputNav, StoryboardSection } from './LayoutComponents';
import { GenerationSummary } from './GenerationSummary';
import { downloadPDF } from '../../services/pdfService';
import { useSound } from '../hooks/useSound';
import { regenerateBTS } from '../../services/geminiService';

// Component Props
interface OutputDisplayProps {
  generatedAssets: GeneratedAssets;
  onScriptSave: (newScript: ScriptBlock[], newCharacters: Character[]) => void;
  onOutlineSave: (newOutline: Scene[]) => void;
  onBtsSave: (newBtsDoc: string) => void;
  onVideoSave: (updatedScene: Scene) => void;
  visualStyle: VisualStyle;
  creativeChoices: {
    theme: RewriteTomorrowTheme;
    arc: EmotionalArcIntensity;
    style: VisualStyle;
    tone: NarrativeTone;
  };
  hasDonated: boolean;
  hasSelectedTier: boolean;
  onOpenMonetization: () => void;
}

export const OutputDisplay: React.FC<OutputDisplayProps> = ({
  generatedAssets,
  onScriptSave,
  onOutlineSave,
  onBtsSave,
  onVideoSave,
  visualStyle,
  creativeChoices,
  hasDonated,
  hasSelectedTier,
  onOpenMonetization
}) => {
    const { script, characters, visualOutline, referenceImages, btsDocument } = generatedAssets;
    const [isVeoKeySelected, setIsVeoKeySelected] = useState<boolean | null>(null);
    const [isRegeneratingBts, setIsRegeneratingBts] = useState(false);
    const playSound = useSound();

    const checkApiKey = useCallback(async () => {
        if ((window as any).aistudio) {
            try {
                const hasKey = await (window as any).aistudio.hasSelectedApiKey();
                setIsVeoKeySelected(hasKey);
            } catch (e) {
                console.error("Error checking API key status:", e);
                setIsVeoKeySelected(false);
            }
        } else {
            console.warn("window.aistudio not found. Assuming no key selected.");
            setIsVeoKeySelected(false);
        }
    }, []);

    useEffect(() => {
        checkApiKey();
    }, [checkApiKey]);

    const handleSelectKey = async () => {
        if ((window as any).aistudio) {
            await (window as any).aistudio.openSelectKey();
            setIsVeoKeySelected(true); // Optimistic update
            checkApiKey(); // Re-verify in the background
        }
    };

    const handleInvalidKeyError = useCallback(() => {
        setIsVeoKeySelected(false);
    }, []);

    const handleCharacterSave = (newCharacters: Character[]) => {
        onScriptSave(script, newCharacters);
    };
    const handleScriptContentSave = (newScript: ScriptBlock[]) => {
        onScriptSave(newScript, characters);
    }
    
    const handleDownloadPDF = () => {
        playSound();
        // If user hasn't selected ANY tier (free or paid), open modal.
        if (!hasDonated && !hasSelectedTier) {
            onOpenMonetization();
        } else {
            // Pass hasDonated state to service to determine if watermark should be added
            downloadPDF(generatedAssets, creativeChoices, hasDonated);
        }
    };

    const handleRegenerateBts = async () => {
        setIsRegeneratingBts(true);
        playSound();
        try {
            const newBts = await regenerateBTS(
                creativeChoices.theme,
                creativeChoices.arc,
                visualStyle,
                creativeChoices.tone,
                script,
                characters,
                visualOutline
            );
            onBtsSave(newBts);
        } catch (e) {
            console.error(e);
            alert("Failed to update BTS document.");
        } finally {
            setIsRegeneratingBts(false);
        }
    };
    
    return (
        <div className="space-y-16 md:space-y-24 pb-32">
            <div className="text-center animate-fade-in">
                <div className="inline-block">
                    <LogoIcon large={true} />
                </div>
                <h1 className="text-4xl md:text-5xl font-extrabold text-white mt-4 bg-gradient-to-r from-cyan-400 to-slate-400 text-transparent bg-clip-text">Blueprint for a Brighter Future</h1>
                <p className="text-text-secondary text-lg mt-2">Generated by your AI creative partner.</p>
            </div>
            
            <div className="flex flex-col items-center animate-fade-in" style={{ animationDelay: '50ms' }}>
                <GenerationSummary choices={creativeChoices} />
            </div>
            
            <OutputNav />

            <StoryboardSection id="characters" title="Characters" style={{ animationDelay: '200ms' }}>
                <CharactersSection characters={characters} onSave={handleCharacterSave} />
            </StoryboardSection>
            
            <StoryboardSection id="script" title="Script" style={{ animationDelay: '400ms' }}>
                <ScriptSection script={script} characters={characters} onSave={handleScriptContentSave} />
            </StoryboardSection>

            <StoryboardSection id="outline" title="Visual Outline" style={{ animationDelay: '600ms' }}>
                <VisualOutlineSection 
                    outline={visualOutline} 
                    characters={characters}
                    onSave={onOutlineSave} 
                    onVideoSave={onVideoSave} 
                    visualStyle={visualStyle} 
                    isVeoKeySelected={isVeoKeySelected}
                    onSelectKey={handleSelectKey}
                    onInvalidKeyError={handleInvalidKeyError}
                />
            </StoryboardSection>

            <StoryboardSection id="moodboard" title="Moodboard" style={{ animationDelay: '800ms' }}>
                <MoodboardSection images={referenceImages} />
            </StoryboardSection>

            <StoryboardSection id="bts" title="Behind The Scenes" style={{ animationDelay: '1000ms' }}>
                <BtsSection 
                    document={btsDocument} 
                    onSave={onBtsSave} 
                    onRegenerate={handleRegenerateBts}
                    isRegenerating={isRegeneratingBts}
                />
            </StoryboardSection>

            <div className="flex justify-center animate-fade-in pt-12" style={{ animationDelay: '1200ms' }}>
                <div className="flex flex-col items-center gap-3">
                    <button 
                        onClick={handleDownloadPDF}
                        className="btn-gold flex items-center gap-3 bg-slate-800/80 text-white px-10 py-5 rounded-full font-bold border border-white/10 hover:border-cyan-400/50 transition-all shadow-xl hover:shadow-cyan-500/30 text-xl tracking-wide group"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 group-hover:animate-bounce" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                        </svg>
                        Download Script & Prompts (PDF)
                    </button>
                    {!hasDonated && (
                        <div className="text-center space-y-1">
                            <p className="text-xs text-slate-500 flex items-center justify-center gap-1">
                                <svg className="w-3 h-3 text-emerald-500" fill="currentColor" viewBox="0 0 20 20"><path d="M5 4a2 2 0 012-2h6a2 2 0 012 2v14l-5-2.5L5 18V4z" /></svg>
                                Support Stichting Earth Rising to unlock full export
                            </p>
                            <p className="text-[10px] text-slate-600">
                                Need help? <a href="mailto:info@earthrising.space" className="hover:text-emerald-400 transition-colors">info@earthrising.space</a>
                            </p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
