
import React, { useState, useEffect, useCallback } from 'react';
import type { GeneratedAssets, ScriptBlock, Scene, Character, VisualStyle, RewriteTomorrowTheme, EmotionalArcIntensity, NarrativeTone } from '../../types';
import { LogoIcon } from '../icons/LogoIcon';
import { CharactersSection } from './CharactersSection';
import { ScriptSection } from './ScriptSection';
import { VisualOutlineSection } from './VisualOutlineSection';
import { MoodboardSection } from './MoodboardSection';
import { BtsSection } from './BtsSection';
import { OutputNav, StoryboardSection } from './LayoutComponents';
import { GenerationSummary } from './GenerationSummary';

// Component Props
interface OutputDisplayProps {
  generatedAssets: GeneratedAssets;
  onScriptSave: (newScript: ScriptBlock[], newCharacters: Character[]) => void;
  onOutlineSave: (newOutline: Scene[]) => void;
  onBtsSave: (newBtsDoc: string) => void;
  onVideoSave: (updatedScene: Scene) => void;
  visualStyle: VisualStyle;
  creativeChoices: {
    theme: RewriteTomorrowTheme;
    arc: EmotionalArcIntensity;
    style: VisualStyle;
    tone: NarrativeTone;
  }
}

export const OutputDisplay: React.FC<OutputDisplayProps> = ({
  generatedAssets,
  onScriptSave,
  onOutlineSave,
  onBtsSave,
  onVideoSave,
  visualStyle,
  creativeChoices,
}) => {
    const { script, characters, visualOutline, referenceImages, btsDocument } = generatedAssets;
    const [isVeoKeySelected, setIsVeoKeySelected] = useState<boolean | null>(null);

    const checkApiKey = useCallback(async () => {
        if ((window as any).aistudio) {
            try {
                const hasKey = await (window as any).aistudio.hasSelectedApiKey();
                setIsVeoKeySelected(hasKey);
            } catch (e) {
                console.error("Error checking API key status:", e);
                setIsVeoKeySelected(false);
            }
        } else {
            console.warn("window.aistudio not found. Assuming no key selected.");
            setIsVeoKeySelected(false);
        }
    }, []);

    useEffect(() => {
        checkApiKey();
    }, [checkApiKey]);

    const handleSelectKey = async () => {
        if ((window as any).aistudio) {
            await (window as any).aistudio.openSelectKey();
            setIsVeoKeySelected(true); // Optimistic update
            checkApiKey(); // Re-verify in the background
        }
    };

    const handleInvalidKeyError = useCallback(() => {
        setIsVeoKeySelected(false);
    }, []);

    const handleCharacterSave = (newCharacters: Character[]) => {
        onScriptSave(script, newCharacters);
    };
    const handleScriptContentSave = (newScript: ScriptBlock[]) => {
        onScriptSave(newScript, characters);
    }
    
    return (
        <div className="space-y-16 md:space-y-24">
            <div className="text-center animate-fade-in">
                <div className="inline-block">
                    <LogoIcon large={true} />
                </div>
                <h1 className="text-4xl md:text-5xl font-extrabold text-white mt-4 bg-gold-reflection text-transparent bg-clip-text">Blueprint for a Brighter Future</h1>
                <p className="text-text-secondary text-lg mt-2">Generated by your AI creative partner.</p>
            </div>
            
            <GenerationSummary choices={creativeChoices} />
            <OutputNav />

            <StoryboardSection id="characters" title="Characters" style={{ animationDelay: '200ms' }}>
                <CharactersSection characters={characters} onSave={handleCharacterSave} />
            </StoryboardSection>
            
            <StoryboardSection id="script" title="Script" style={{ animationDelay: '400ms' }}>
                <ScriptSection script={script} characters={characters} onSave={handleScriptContentSave} />
            </StoryboardSection>

            <StoryboardSection id="outline" title="Visual Outline" style={{ animationDelay: '600ms' }}>
                <VisualOutlineSection 
                    outline={visualOutline} 
                    onSave={onOutlineSave} 
                    onVideoSave={onVideoSave} 
                    visualStyle={visualStyle} 
                    isVeoKeySelected={isVeoKeySelected}
                    onSelectKey={handleSelectKey}
                    onInvalidKeyError={handleInvalidKeyError}
                />
            </StoryboardSection>

            <StoryboardSection id="moodboard" title="Moodboard" style={{ animationDelay: '800ms' }}>
                <MoodboardSection images={referenceImages} />
            </StoryboardSection>

            <StoryboardSection id="bts" title="Behind The Scenes" style={{ animationDelay: '1000ms' }}>
                <BtsSection document={btsDocument} onSave={onBtsSave} />
            </StoryboardSection>
        </div>
    );
}
